const types = {
  ALL_SERVICES: "@salao/ALL_SERVICES",
  UPDATE_FORM: "@salao/UPDATE_FORM",
  UPDATE_SCHEDULE: "@salao/UPDATE_SCHEDULE",
  UPDATE_SCHEDULING: "@salao/UPDATE_SCHEDULING",
  FILTER_SCHEDULE: "@salao/FILTER_SCHEDULE",
  DATA_SCHEDULING: "@salao/DATA_SCHEDULING",
  UPDATE_COLLABORATORS: "@salao/COLLABORATORS",
  MODAL_SPECIALIST: "@salao/MODAL_SPECIALIST",
  PAYMENT_METHOD: "@salao/PAYMENT_METHOD",
  MODAL_PAYMENT_METHOD: "@salao/MODAL_PAYMENT_METHOD",
};

export default types;
